# Site settings
title: "TIL: UE4"
email: ue4@mmlac.com
description: > # this means to ignore newlines until "baseurl:"
  Today I Learned: Unreal Engine 4 is a small blog about me learning UE4
  with the goal of building procedurally generated terrain and allow
  in-game deformation of such.
baseurl: "/tilue4" # the subpath of your site, e.g. /blog/
url: "http://www.mmlac.com" # the base hostname & protocol for your site
twitter_username: mLachinger
github_username: mmlac
ue4_username: shox

# Build settings
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM
